// Generado por descargarMapas.mjs — 2026-07-23T20:19:49.992Z
// NO EDITAR A MANO. Las URLs de origen viven en fuentesMapas.mjs;
// este archivo solo apunta a las copias locales ya descargadas
// (y simplificadas si pesaban más de 200 KB).
export const mapasProvincias = {
  "Spain": "/data/spain.json",
  "France": "/data/france.json",
  "Italy": "/data/italy.json",
  "Germany": "/data/germany.json",
  "Portugal": "/data/portugal.json",
  "United Kingdom": "/data/united-kingdom.json",
  "Ireland": "/data/ireland.json",
  "Netherlands": "/data/netherlands.json",
  "Belgium": "/data/belgium.json",
  "Switzerland": "/data/switzerland.json",
  "Austria": "/data/austria.json",
  "Greece": "/data/greece.json",
  "Turkey": "/data/turkey.json",
  "Poland": "/data/poland.json",
  "Czechia": "/data/czechia.json",
  "Czech Republic": "/data/czech-republic.json",
  "Romania": "/data/romania.json",
  "Ukraine": "/data/ukraine.json",
  "Sweden": "/data/sweden.json",
  "Norway": "/data/norway.json",
  "Finland": "/data/finland.json",
  "Denmark": "/data/denmark.json",
  "Russia": "/data/russia.json",
  "Japan": "/data/japan.json",
  "China": "/data/china.json",
  "India": "/data/india.json",
  "South Korea": "/data/south-korea.json",
  "North Korea": "/data/north-korea.json",
  "Philippines": "/data/philippines.json",
  "Indonesia": "/data/indonesia.json",
  "Malaysia": "/data/malaysia.json",
  "Thailand": "/data/thailand.json",
  "Nepal": "/data/nepal.json",
  "Pakistan": "/data/pakistan.json",
  "Afghanistan": "/data/afghanistan.json",
  "Mongolia": "/data/mongolia.json",
  "Bhutan": "/data/bhutan.json",
  "Maldives": "/data/maldives.json",
  "Brunei": "/data/brunei.json",
  "Singapore": "/data/singapore.json",
  "East Timor": "/data/east-timor.json",
  "Timor-Leste": "/data/timor-leste.json",
  "Australia": "/data/australia.json",
  "New Zealand": "/data/new-zealand.json",
  "Papua New Guinea": "/data/papua-new-guinea.json",
  "Fiji": "/data/fiji.json",
  "Solomon Islands": "/data/solomon-islands.json",
  "Vanuatu": "/data/vanuatu.json",
  "Samoa": "/data/samoa.json",
  "Tonga": "/data/tonga.json",
  "Kiribati": "/data/kiribati.json",
  "United States of America": "/data/united-states-of-america.json",
  "United States": "/data/united-states.json",
  "Canada": "/data/canada.json",
  "Mexico": "/data/mexico.json",
  "Brazil": "/data/brazil.json",
  "Argentina": "/data/argentina.json",
  "Chile": "/data/chile.json",
  "Colombia": "/data/colombia.json",
  "Peru": "/data/peru.json",
  "Venezuela": "/data/venezuela.json",
  "Ecuador": "/data/ecuador.json",
  "Bolivia": "/data/bolivia.json",
  "Paraguay": "/data/paraguay.json",
  "Uruguay": "/data/uruguay.json",
  "Guyana": "/data/guyana.json",
  "Suriname": "/data/suriname.json",
  "Cuba": "/data/cuba.json",
  "Jamaica": "/data/jamaica.json",
  "Haiti": "/data/haiti.json",
  "Dominican Republic": "/data/dominican-republic.json",
  "Bahamas": "/data/bahamas.json",
  "The Bahamas": "/data/the-bahamas.json",
  "Trinidad and Tobago": "/data/trinidad-and-tobago.json",
  "Belize": "/data/belize.json",
  "Costa Rica": "/data/costa-rica.json",
  "Panama": "/data/panama.json",
  "Guatemala": "/data/guatemala.json",
  "Honduras": "/data/honduras.json",
  "Nicaragua": "/data/nicaragua.json",
  "El Salvador": "/data/el-salvador.json",
  "South Africa": "/data/south-africa.json",
  "Nigeria": "/data/nigeria.json",
  "Kenya": "/data/kenya.json",
  "Morocco": "/data/morocco.json",
  "Egypt": "/data/egypt.json",
  "Iceland": "/data/iceland.json",
  "Croatia": "/data/croatia.json",
  "Slovenia": "/data/slovenia.json",
  "Slovakia": "/data/slovakia.json",
  "Hungary": "/data/hungary.json",
  "Bulgaria": "/data/bulgaria.json",
  "Serbia": "/data/serbia.json",
  "Bosnia and Herzegovina": "/data/bosnia-and-herzegovina.json",
  "Montenegro": "/data/montenegro.json",
  "North Macedonia": "/data/north-macedonia.json",
  "Macedonia": "/data/macedonia.json",
  "Kosovo": "/data/kosovo.json",
  "Albania": "/data/albania.json",
  "Estonia": "/data/estonia.json",
  "Latvia": "/data/latvia.json",
  "Lithuania": "/data/lithuania.json",
  "Moldova": "/data/moldova.json",
  "Belarus": "/data/belarus.json",
  "Georgia": "/data/georgia.json",
  "Armenia": "/data/armenia.json",
  "Azerbaijan": "/data/azerbaijan.json",
  "Kazakhstan": "/data/kazakhstan.json",
  "Uzbekistan": "/data/uzbekistan.json",
  "Turkmenistan": "/data/turkmenistan.json",
  "Kyrgyzstan": "/data/kyrgyzstan.json",
  "Tajikistan": "/data/tajikistan.json",
  "Vietnam": "/data/vietnam.json",
  "Cambodia": "/data/cambodia.json",
  "Laos": "/data/laos.json",
  "Myanmar": "/data/myanmar.json",
  "Bangladesh": "/data/bangladesh.json",
  "Sri Lanka": "/data/sri-lanka.json",
  "Israel": "/data/israel.json",
  "Palestine": "/data/palestine.json",
  "Jordan": "/data/jordan.json",
  "Lebanon": "/data/lebanon.json",
  "Syria": "/data/syria.json",
  "Cyprus": "/data/cyprus.json",
  "Saudi Arabia": "/data/saudi-arabia.json",
  "United Arab Emirates": "/data/united-arab-emirates.json",
  "Qatar": "/data/qatar.json",
  "Kuwait": "/data/kuwait.json",
  "Bahrain": "/data/bahrain.json",
  "Oman": "/data/oman.json",
  "Yemen": "/data/yemen.json",
  "Iran": "/data/iran.json",
  "Iraq": "/data/iraq.json",
  "Luxembourg": "/data/luxembourg.json",
  "Malta": "/data/malta.json",
  "Monaco": "/data/monaco.json",
  "Andorra": "/data/andorra.json",
  "San Marino": "/data/san-marino.json",
  "Vatican": "/data/vatican.json",
  "Liechtenstein": "/data/liechtenstein.json",
  "Ghana": "/data/ghana.json",
  "Senegal": "/data/senegal.json",
  "Tunisia": "/data/tunisia.json",
  "Algeria": "/data/algeria.json",
  "Libya": "/data/libya.json",
  "Sudan": "/data/sudan.json",
  "South Sudan": "/data/south-sudan.json",
  "Ethiopia": "/data/ethiopia.json",
  "Somalia": "/data/somalia.json",
  "Djibouti": "/data/djibouti.json",
  "Eritrea": "/data/eritrea.json",
  "Tanzania": "/data/tanzania.json",
  "United Republic of Tanzania": "/data/united-republic-of-tanzania.json",
  "Uganda": "/data/uganda.json",
  "Rwanda": "/data/rwanda.json",
  "Burundi": "/data/burundi.json",
  "Zambia": "/data/zambia.json",
  "Zimbabwe": "/data/zimbabwe.json",
  "Namibia": "/data/namibia.json",
  "Botswana": "/data/botswana.json",
  "Mozambique": "/data/mozambique.json",
  "Angola": "/data/angola.json",
  "Malawi": "/data/malawi.json",
  "Democratic Republic of the Congo": "/data/democratic-republic-of-the-congo.json",
  "Republic of the Congo": "/data/republic-of-the-congo.json",
  "Congo": "/data/congo.json",
  "Gabon": "/data/gabon.json",
  "Cameroon": "/data/cameroon.json",
  "Central African Republic": "/data/central-african-republic.json",
  "Chad": "/data/chad.json",
  "Niger": "/data/niger.json",
  "Mali": "/data/mali.json",
  "Burkina Faso": "/data/burkina-faso.json",
  "Ivory Coast": "/data/ivory-coast.json",
  "Cote d'Ivoire": "/data/cote-d-ivoire.json",
  "Guinea": "/data/guinea.json",
  "Guinea-Bissau": "/data/guinea-bissau.json",
  "Sierra Leone": "/data/sierra-leone.json",
  "Liberia": "/data/liberia.json",
  "Togo": "/data/togo.json",
  "Benin": "/data/benin.json",
  "Mauritania": "/data/mauritania.json",
  "Gambia": "/data/gambia.json",
  "Equatorial Guinea": "/data/equatorial-guinea.json",
  "Lesotho": "/data/lesotho.json",
  "Eswatini": "/data/eswatini.json",
  "Swaziland": "/data/swaziland.json",
  "Madagascar": "/data/madagascar.json",
  "Comoros": "/data/comoros.json",
  "Cape Verde": "/data/cape-verde.json",
  "Sao Tome and Principe": "/data/sao-tome-and-principe.json",
  "Seychelles": "/data/seychelles.json",
  "Mauritius": "/data/mauritius.json"
};
